# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Demo Nextjs App"
client_id = "13c5c3746574bfbd5fb7adac5cf4d07f"
application_url = "https://shopify-next-js-prisma-app.vercel.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://shopify-next-js-prisma-app.vercel.app/api/auth/tokens",
  "https://shopify-next-js-prisma-app.vercel.app/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[app_proxy]
url = "https://shopify-next-js-prisma-app.vercel.app/api/proxy_route"
subpath = "next-proxy"
prefix = "apps"

[pos]
embedded = false
